### ISSUE TITLE
request for ros2 support

### ISSUE THREAD

**Issue by JaehyunShim** [Autoware-AI/qpoases_vendor#4]
### Description

First of all, I would like to say thank you very much for maintaining this repository and releasing it in [every different version](https://index.ros.org/search/?term=qpoases_vendor). I wonder if you have a plan to support this repository in the ROS2 versions (preferably foxy first). It will only need to make some changes in CMakelist.txt and package.xml files.

Jaehyun

**Comment by JWhitleyWork** [comment]
Sorry for the delay. Release is pending for `foxy`: https://github.com/ros/rosdistro/pull/30022

The `subversion` rosdep key is missing for RHEL so once that is added, I'll get it released for `galactic` and `rolling`.
